#print('静夜思’‘\n’‘李白’‘\n’‘床前明月光’’\n’‘疑是地上霜’‘\n’‘举头望明月’‘\n’‘低头思故乡’）
print(1)
print(2)
print(3)
print(4)
print(5)
print(6)
print(7)
print(8)
print(9)
print(10)
print('      *')
print('    *   *')
print('   *     *')
print(' *    *   *')
print('*   *   *   *')
print('      *        ')
print('      *')
print('      *')
